on:
  pull_request:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml  
  
    - name: Build
      run: dotnet build --configuration Release
  
    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Package nuget
      run: dotnet pack --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}

    - name: Upload package for publishing
      uses: actions/upload-artifact@v3
      with:
        name: DbUp.SerilogUpgradeLog.nupkg
        path: ${{ github.workspace }}/package/DbUp.SerilogUpgradeLog.**.nupkg
        if-no-files-found: error
        retention-days: 1

  
  package:
    name: Publish
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download package from build
      uses: actions/download-artifact@v3
      with:
        name: DbUp.SerilogUpgradeLog.nupkg

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.workspace }}
      
    - name: Prep publish to github
      run: dotnet nuget add source --username chenery-nz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/chenery-nz/SerilogUpgradeLog/index.json"

    - name: Publish to GitHub packages
      run: dotnet nuget push ${{ github.workspace }}/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"